### ISSUE TITLE
Баг с залипанием кнопки

### ISSUE THREAD

**Issue by Kukushechka7-ezx** [Sokol-Games-GmbH/PixelCombats.PublicApi#104]
Если удерживать кнопку удара, и нажать вверху на таймер - то кнопка зажметмя, могу скинуть видио

**Comment by Kukushechka7-ezx** [comment]
@kkohno ролик скинул в ВК https://vk.com/makushkasuper

**Comment by kkohno** [comment]
ок, решим

**Comment by Kukushechka7-ezx** [comment]
Константин, можно вопрос не по теме да? Что с тестером? Посмотри я кидал с 3 аккаунтов тут баги... Их уже штук 20 накопилось, на 5-6 то хватит? Если что айди C002224F3666744D

**Comment by forwork10** [comment]
> Константин, можно вопрос не по теме да? Что с тестером? Посмотри я кидал с 3 аккаунтов тут баги... Их уже штук 20 накопилось, на 5-6 то хватит? Если что айди C002224F3666744D

где ты кидал баги? если про гитхаб, то ты накидал всякие случайные баги с одного акка, я считаю ты не заслуживаешь ничего...

**Comment by kkohno** [comment]
> C002224F3666744D

Выдал лвл.

**Comment by Kukushechka7-ezx** [comment]
Благодарю

**Comment by Kukushechka7-ezx** [comment]
Погодите , смотрите 
Это все новые баги которые кидал Я с 3 акков:

Баг с рассинхроном
Баг с листом сервера
Баг с залипанием кнопки
Баг с событием OnRequest
Баг с флаем
Ошибка на карте action
Накрутка оценок.

Можете ещё чуть выдать?) Просто много так писал этого

**Comment by Kukushechka7-ezx** [comment]
Враньё? Что враньё? Недобаги? Покажи хоть 1. + Я кидал с 3 и могу подтвердить.

**Comment by forwork10** [comment]
подтверди

**Comment by forwork10** [comment]
> Враньё? Что враньё? Недобаги? Покажи хоть 1. + Я кидал с 3 и могу подтвердить.

правильнее будет потребовать показать баги - их нет.

**Comment by Kukushechka7-ezx** [comment]
Кого нет? Ты типо сам не можешь посмотреть

**Comment by forwork10** [comment]
типо я смотрю и не вижу их...

**Comment by Kukushechka7-ezx** [comment]
Рассинхрон частый, тупо могут сппвны сбросится.

С листом тоже, на индекс вперёд идёт

С загрузкой сам проверь, событие работает не правильно

Залипание уже подтвердили

Чекни сам... Я писал ему в ВК

**Comment by forwork10** [comment]
Всё это - рандом баги, никакой инструкции как их повторить ты не дал

**Comment by Kukushechka7-ezx** [comment]
Кого рандомные,ты долбаеб? 

С листов ты быстро нажимаешь вперёд 

С залипанием выше описано

Загрузка это событие OnLoad

**Comment by forwork10** [comment]
видео нужно, а где проблемы с апи - пример кода

**Comment by forwork10** [comment]
если ты баги не умеешь оформлять даже...

**Comment by Kukushechka7-ezx** [comment]
"не умеешь оформлять" при этом КОХНО все понял

**Comment by Kukushechka7-ezx** [comment]
![Uploading Screenshot_2023-09-15-21-54-12-152_com.android.chrome.jpg…]()

**Comment by forwork10** [comment]
> ![Uploading Screenshot_2023-09-15-21-54-12-152_com.android.chrome.jpg…]()
> 

?

**Comment by rtemon** [comment]
Не по теме знаю, но когда античит? У меня столько айди читеров, вот чел с читом 569D4364ED9DB55F, и таких много. Надеюсь античит усилят, хоть читеров и реже стали попадаться, но всё-же попадаются, это печально

**Comment by rtemon** [comment]
**типо античит грубо говоря г•вно**
