### ISSUE TITLE
Ошибка в событиях OnDeath или OnKill.

### ISSUE THREAD

**Issue by Kukushechka7-ezx** [Sokol-Games-GmbH/PixelCombats.PublicApi#115]
Если в событиях описанных выше, будет ошибка внутри функции - то игрок будет умирать только локально.

**Comment by forwork10** [comment]
это вовсе не баг... при ошибке внутри функции она должна завершать выполнение... тебе нужно просто уметь код писать научиться

**Comment by Kukushechka7-ezx** [comment]
Баг... Тут это не как не связано со смертьбн... Сначало игрок должен умирать, а потом вызывать событие

**Comment by Kukushechka7-ezx** [comment]
@kkohno так ведь?

**Comment by forwork10** [comment]
если в событии смерти происходит ошибка, то выполнение дальнейших функций, таких как запуск таймера возрождения, не происходит

**Comment by forwork10** [comment]
ты ничего в этом не понимаешь, глупышка

**Comment by Kukushechka7-ezx** [comment]
Глупец) взял и мои слова перефразировал! Ахуеть! И как с таким глупым пубертатным хуесосом общатся?

**Comment by forwork10** [comment]
ну я понимаю что ты злишься, ты не прав оказался... зачем так агрессировать и вводить в заблуждение всех?)

**Comment by Kukushechka7-ezx** [comment]
Где не прав?) То что я тебе на ошибку оказал, а ты не слышишь мнение других более умных людей? Ну...

**Comment by forwork10** [comment]
какую ещё ошибку? я тебе сказал как повторить баг, это даже не связано с ивентами..

**Comment by Kukushechka7-ezx** [comment]
Тупая овца...

**Comment by Kukushechka7-ezx** [comment]
Я больше не могу с тобой общаться, пингани как поумнеешь, ты реально глупый так нечего и не понял

**Comment by forwork10** [comment]
еще раз повторю, ты только себя этими словами утешить можешь, если ты написал бред, он не станет действительностью

**Comment by kkohno** [comment]
поидее должен прерваться Ваш код, однако внешнее наше все должно отработать

**Comment by Kukushechka7-ezx** [comment]
Он вообще игрок не умерает

**Comment by Kukushechka7-ezx** [comment]
Посмотрите что я вам написал в Issue "залипание кнопок"

**Comment by forwork10** [comment]
> Он вообще игрок не умерает 

  😂😂😂😂😂

**Comment by forwork10** [comment]
нормально он умирает... просто ошибка интерфейса из-за прерывания функции
