### ISSUE TITLE
String.ToRegular();

### ISSUE THREAD

**Issue by Kukushechka7-ezx** [Sokol-Games-GmbH/PixelCombats.PublicApi#117]
Сделать специально для шрифта эту функцию, которая будет выделять заглавные буквы... А не все большие

**Comment by forwork10** [comment]
Не понятно.... чем ты опять не доволен клоун👎🏿)?

**Comment by forwork10** [comment]
если это ваша идея, то не следует писать это в issue... Удалите.

**Comment by Kukushechka7-ezx** [comment]
Нет
