### ISSUE TITLE
Накрученные режимы 

### ISSUE THREAD

**Issue by Kukushechka7-ezx** [Sokol-Games-GmbH/PixelCombats.PublicApi#118]
6, 888, 666, 555, 444, 333 - айди всех накрученных режимов , по возможности удалите. Там ещё есть накрученная карта, на 1 месте

**Comment by kkohno** [comment]
да, есть там с накруткой проблема, будем бороться.

**Comment by Kukushechka7-ezx** [comment]
Удалите их..

**Comment by forwork10** [comment]
Там в верху списка у всех режимов есть накрутка, где-то 5 первых режимов. а все потому что там какой-то дебил накрутил плохих оценок на хорошие режимы, вот пришлось всё восстановить )
