### ISSUE TITLE
Баг со сменой ника.

### ISSUE THREAD

**Issue by Kukushechka7-ezx** [Sokol-Games-GmbH/PixelCombats.PublicApi#119]
https://t.me/code1r скинул сюда

**Comment by forwork10** [comment]
зачем сюда это кидать если бага нет?
[CLOSE ISSUE - INVALID]....

**Comment by Kukushechka7-ezx** [comment]
Почему нет? В тг скинул ему... Там баг такой что тебе лучше не знать

**Comment by kkohno** [comment]
> https://t.me/code1r скинул сюда

там баги не выкладываем

**Comment by Kukushechka7-ezx** [comment]
Так а как тут ролик то поставить? @kkohno
