### ISSUE TITLE
Баг с количеством онлайна на режиме

### ISSUE THREAD

**Issue by forwork10** [Sokol-Games-GmbH/PixelCombats.PublicApi#122]
Если комната с определенным режимом полная, то игра её не считает. На скрине видно как в списке режимов у редактора 12 игроков, но если посчитать игроков в списке комнат с этим режимом, их будет на 3 больше - именно столько игроков в полных комнатах. ![Screenshot_20230918-164637_Pixel Combats 2.jpg](https://github.com/Sokol-Games-GmbH/PixelCombats.PublicApi/assets/131859196/e6cf8128-6d18-41d5-b9a2-1629a535a25c)

![Screenshot_20230918-164627_Pixel Combats 2.jpg](https://github.com/Sokol-Games-GmbH/PixelCombats.PublicApi/assets/131859196/541ba8cb-6a33-4788-a73a-68a4cae94244)

**Comment by Kukushechka7-ezx** [comment]
Добавлю, если комната полная то тупо не будет создаваться раздел с нею - технически правильно. Но нужно было бы как то обдумать это...

**Comment by forwork10** [comment]
"Технически правильно" - ты щас бред написал, да еще в стиле какого-то разработчика, который разбирается...

**Comment by Kukushechka7-ezx** [comment]
И где бред? Расскажи

**Comment by forwork10** [comment]
Не должно так быть, должно считать все комнаты, а не только свободные, например если годный режим переполнен то наверняка кто-то захочет подождать пока какая-то комнаты освободится, или создать свою

**Comment by Kukushechka7-ezx** [comment]
Я про то что вообще будет показан он в списке. Тут всё верно - а то нажмут на режим а там 0 серверов

**Comment by forwork10** [comment]
> Я про то что вообще будет показан он в списке. Тут всё верно - а то нажмут на режим а там 0 серверов

Ну и создадут свою комнату... Там конечно бывает когда топовые режимы, например зомби- и все комнаты переполнены, тут уже можно переделать интерфейс чтобы видели что есть полные комнаты...

**Comment by forwork10** [comment]
А то что сейчас происходит - так быть явно не должно и никто так не задумывал это... Поэтому не вводите пожалуйста в заблуждение всех...

**Comment by Kukushechka7-ezx** [comment]
@kkohno скажите уже ему ...

**Comment by kkohno** [comment]
так, спасибо за описание бага, в ближайшее время исправим

**Comment by kkohno** [comment]
исправлено в 502
