### ISSUE TITLE
Недоработка в магазине тестера. #BUG

### ISSUE THREAD

**Issue by ZhenyaMartynov** [Sokol-Games-GmbH/PixelCombats.PublicApi#145]
![Screenshot_2023-10-22-03-29-09-099_com pixel gun combats](https://github.com/Sokol-Games-GmbH/PixelCombats.PublicApi/assets/146564992/c7f32a86-64ae-43a9-8d7a-eb3a60353eeb)
![Screenshot_2023-10-22-03-29-06-486_com pixel gun combats](https://github.com/Sokol-Games-GmbH/PixelCombats.PublicApi/assets/146564992/144221e4-86de-443e-aa7c-f2a48ee036ea)

Вместо того чтобы добавлять новое оружие в магазин просто меняйте его цену

**Comment by forwork10** [comment]
Ну тут нет бага, а в магазине отдельную вкладку сделали чтобы например у тестеров могли быть дополнительные предметы... например тот же сундук серебряный... И иногда может понадобится купить оружие не в магазине тестера, а в обычном, например когда нужна аренда на день...

**Comment by kkohno** [comment]
Бага не вижу... вроде все ок. 2 слота тойже пушки - одна на 1 час, вторая на 6 часов.

**Comment by ZhenyaMartynov** [comment]
Зачем?... Кто захочет арендовать на час если можно на 6
