### ISSUE TITLE
Модерация issues

### ISSUE THREAD

**Issue by forwork10** [Sokol-Games-GmbH/PixelCombats.PublicApi#150]
предлагаю дать мне возможность фильтровать не допустимы записи, например вот эти: 
https://github.com/Sokol-Games-GmbH/PixelCombats.PublicApi/issues/149
https://github.com/Sokol-Games-GmbH/PixelCombats.PublicApi/issues/148
(это должно находиться в дискуссиях)

**Comment by kkohno** [comment]
мы не даем модерацию игрокам
