### ISSUE TITLE
Сохраняется флай при переходе в другую команду #BUG

### ISSUE THREAD

**Issue by nikusha-diqsaid** [Sokol-Games-GmbH/PixelCombats.PublicApi#153]
**Когда игрок с флаем и ему уберают флай потом же кидая его в другую команду, флай сохраняется, и та же высота.**

**Comment by forwork10** [comment]
Не баг это, просто не прописали сброс полёта при спавне...

**Comment by kkohno** [comment]
все верно написано - флай был на конкретного игрока а не на команду, вот он и летает дальше

**Comment by forwork10** [comment]
> все верно написано - флай был на конкретного игрока а не на команду, вот он и летает дальше

но если запретить полёт в то время когда игрок находится в полёте, то он всеравно останется в воздухе.

Необходимо выключать IsFlyingMode в классе FpPlayerData.

**Comment by kkohno** [comment]
> но если запретить полёт в то время когда игрок находится в полёте, то он всеравно останется в воздухе.

это похоже на баг, который хорошо бы оформить
