### ISSUE TITLE
Unity markup

### ISSUE THREAD

**Issue by forwork10** [Sokol-Games-GmbH/PixelCombats.PublicApi#160]
Просьба ограничить исполнение тега quad, также добавить интервал между отправкой сообщений.
Например данное сообщение может засрать всю панель чата:
﷽﷽﷽﷽﷽﷽﷽﷽<quаd size=-1999> (тут русскую букву "а" поставил, гитхаб тоже это как тег понимает)
![jhvm5ElgqOA.jpg](https://github.com/Sokol-Games-GmbH/PixelCombats.PublicApi/assets/131859196/c989e088-a232-4139-a45c-8ebc62815f2c)

![yXMAcMkHoa8.jpg](https://github.com/Sokol-Games-GmbH/PixelCombats.PublicApi/assets/131859196/ea63011f-038c-4140-ab7c-af96ef9ac644)

**Comment by kkohno** [comment]
да, помойка реально, походу нужно будет там поправлять в чате.

**Comment by kkohno** [comment]
частично исправлено, с версии 505 нельзя писать текст в чат с Markup
