### ISSUE TITLE
2 mac-10 в магазине тестеровщика

### ISSUE THREAD

**Issue by Vladislav894** [Sokol-Games-GmbH/PixelCombats.PublicApi#194]
Ошибку повторять даже не надо, зайдя в магазин тестера можно заметить сразу 2 MAC-10. Первый 19-й по счёту, а второй 24-й. Причём второй только выпадает. Просьба пофиксить эту ошибку.
Id: 2BC6944AD0C25D8
![Screenshot_20231208-135232](https://github.com/Sokol-Games-GmbH/PixelCombats.PublicApi/assets/148636358/ce9b3b3a-89fc-438c-a90e-35d76266e568)
![Screenshot_20231208-135224](https://github.com/Sokol-Games-GmbH/PixelCombats.PublicApi/assets/148636358/e3ea8332-0eda-49b3-a35b-829f95335a6e)

**Comment by kkohno** [comment]
разное время аренды
