### ISSUE TITLE
Чё-то не понятно

### ISSUE THREAD

**Issue by Vladislav894** [Sokol-Games-GmbH/PixelCombats.PublicApi#201]
Какой-то контракт
![Screenshot_2023-12-20-21-56-50-378_com pixel gun combats](https://github.com/Sokol-Games-GmbH/PixelCombats.PublicApi/assets/148636358/e5d58e10-c86f-46cc-91ee-9efef2a7d8e3)

**Comment by kkohno** [comment]
это новые миссии
