### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by SIANIE19HW** [Sokol-Games-GmbH/PixelCombats.PublicApi#214]
Опечатка в миссиях. Где написано подстрелить 18 врагов и сделать 18 фрагов.
Айди:963D969B822B6878 
![Screenshot_20231226_151040_com.pixel.gun.combats.jpg](https://github.com/Sokol-Games-GmbH/PixelCombats.PublicApi/assets/154672418/4d50cb88-c3ce-4245-877c-05a760a012d0)

**Comment by Evgene82** [comment]
Подстрелить ВРАГОВ

**Comment by lifeHells** [comment]
нет опечатки

**Comment by kkohno** [comment]
Ну фраг это кил и враг это разные вещи
