### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by SIANIE19HW** [Sokol-Games-GmbH/PixelCombats.PublicApi#215]
Какой то странный узор на комнате.
![Screenshot_20231226_155848_com.pixel.gun.combats.jpg](https://github.com/Sokol-Games-GmbH/PixelCombats.PublicApi/assets/154672418/72675eb3-f96e-4f21-9091-6680b2c69b4f)

![Screenshot_20231226_155844_com.pixel.gun.combats.jpg](https://github.com/Sokol-Games-GmbH/PixelCombats.PublicApi/assets/154672418/da2abb87-014d-47d0-a80b-03f11eb53790)

Айди:963D969B822B6878

**Comment by lifeHells** [comment]
обозначения

**Comment by kkohno** [comment]
какой узор? это обозначение, что карта лонг - длинная))
