### ISSUE TITLE
client.js not found - ищет файл со старого АПИ

### ISSUE THREAD

**Issue by SobakaBarabaka74** [Sokol-Games-GmbH/PixelCombats.PublicApi#254]
На версии 1.538 при обновлении репы с гита ищет файл client.js, хотя АПИ новый

**Comment by justqstn** [comment]
ты даун просто

**Comment by SobakaBarabaka74** [comment]
Джаст в очередной раз обосрался? Будешь с Кохно спорить по поводу моей неправоты?)

**Comment by forwork10** [comment]
> Джаст в очередной раз обосрался? Будешь с Кохно спорить по поводу моей неправоты?) 

нет, он не будет спорить по поводу твоей НЕПРАВОТЫ, ибо джаст согласен с этим.

**Comment by forwork10** [comment]
> На версии 1.538 при обновлении репы с гита ищет файл client.js, хотя АПИ новый

ты даун просто

**Comment by SobakaBarabaka74** [comment]
> Джаст в очередной раз обосрался? Будешь с Кохно спорить по поводу моей неправоты?)

![Screenshot_2024-03-05-11-06-53-689_com android chrome](https://github.com/Sokol-Games-GmbH/PixelCombats.PublicApi/assets/153353273/ab10578f-5d5e-4e67-b662-266468af5e09)

**Comment by forwork10** [comment]
> На версии 1.538 при обновлении репы с гита ищет файл client.js, хотя АПИ новый

ничего там не ищет, если не добавлять этот файл ниче не случится

**Comment by SobakaBarabaka74** [comment]
> > На версии 1.538 при обновлении репы с гита ищет файл client.js, хотя АПИ новый
> 
> ничего там не ищет, если не добавлять этот файл ниче не случится

Зачем тебе его добавлять? Это не должно так работать, выше приложил скрин

**Comment by forwork10** [comment]
> > > На версии 1.538 при обновлении репы с гита ищет файл client.js, хотя АПИ новый
> > 
> > ничего там не ищет, если не добавлять этот файл ниче не случится
> 
> Зачем тебе его добавлять? Это не должно так работать, выше приложил скрин

тебе мешает чтоли?)

**Comment by SobakaBarabaka74** [comment]
> > > > На версии 1.538 при обновлении репы с гита ищет файл client.js, хотя АПИ новый
> > > 
> > > 
> > > ничего там не ищет, если не добавлять этот файл ниче не случится
> > 
> > 
> > Зачем тебе его добавлять? Это не должно так работать, выше приложил скрин
> 
> тебе мешает чтоли?)

Допустим мешает, и?

**Comment by forwork10** [comment]
> > > > > На версии 1.538 при обновлении репы с гита ищет файл client.js, хотя АПИ новый
> > > > 
> > > > 
> > > > ничего там не ищет, если не добавлять этот файл ниче не случится
> > > 
> > > 
> > > Зачем тебе его добавлять? Это не должно так работать, выше приложил скрин
> > 
> > тебе мешает чтоли?)
> 
> Допустим мешает, и? 

ну вот ты даун получается - всё ведёт к этому факту

**Comment by SobakaBarabaka74** [comment]
> > > > > > На версии 1.538 при обновлении репы с гита ищет файл client.js, хотя АПИ новый
> > > > > 
> > > > > 
> > > > > ничего там не ищет, если не добавлять этот файл ниче не случится
> > > > 
> > > > 
> > > > Зачем тебе его добавлять? Это не должно так работать, выше приложил скрин
> > > 
> > > 
> > > тебе мешает чтоли?)
> > 
> > 
> > Допустим мешает, и?
> 
> ну вот ты даун получается - всё ведёт к этому факту

Ну ты реально долбаеб спт, опять хуйню несёшь? Обиженный жизнь

**Comment by forwork10** [comment]
> > > > > > > На версии 1.538 при обновлении репы с гита ищет файл client.js, хотя АПИ новый
> > > > > > 
> > > > > > 
> > > > > > ничего там не ищет, если не добавлять этот файл ниче не случится
> > > > > 
> > > > > 
> > > > > Зачем тебе его добавлять? Это не должно так работать, выше приложил скрин
> > > > 
> > > > 
> > > > тебе мешает чтоли?)
> > > 
> > > 
> > > Допустим мешает, и?
> > 
> > ну вот ты даун получается - всё ведёт к этому факту
> 
> Ну ты реально долбаеб спт, опять хуйню несёшь? Обиженный жизнь

что я не так сказал?) ты ведь даун

**Comment by SobakaBarabaka74** [comment]
> > > > > > > > На версии 1.538 при обновлении репы с гита ищет файл client.js, хотя АПИ новый
> > > > > > > 
> > > > > > > 
> > > > > > > ничего там не ищет, если не добавлять этот файл ниче не случится
> > > > > > 
> > > > > > 
> > > > > > Зачем тебе его добавлять? Это не должно так работать, выше приложил скрин
> > > > > 
> > > > > 
> > > > > тебе мешает чтоли?)
> > > > 
> > > > 
> > > > Допустим мешает, и?
> > > 
> > > 
> > > ну вот ты даун получается - всё ведёт к этому факту
> > 
> > 
> > Ну ты реально долбаеб спт, опять хуйню несёшь? Обиженный жизнь
> 
> что я не так сказал?) ты ведь даун

А слабо пояснить?

**Comment by forwork10** [comment]
> А слабо пояснить? 
ок, ты глупый школьник который ничего толком не умеет, но при этом думаешь что очень умный и постоянно выёбываешься) копируешь манеры своих кумиров чтобы казаться лучше. Ты дохуя раз проигрывал в спорах и уходил, высирая какой то рофл бред, а на следующий день начинал всё сначала. Ты просто ебланище которое очень хочет внимание.

**Comment by SobakaBarabaka74** [comment]
> > А слабо пояснить?
> > ок, ты глупый школьник который ничего толком не умеет, но при этом думаешь что очень умный и постоянно выёбываешься) копируешь манеры своих кумиров чтобы казаться лучше. Ты дохуя раз проигрывал в спорах и уходил, высирая какой то рофл бред, а на следующий день начинал всё сначала. Ты просто ебланище которое очень хочет внимание.
Ты блять на Луа скрипты пишешь, и мне че то предъявляешь? Да тебе и 15 нету. Что я там копирую, пример приведи (я кстати не пишу как Кохно ну ВЕЗДЕ почти, как ты)). Значит я внимания хочу?) а кто как пёсик скачет рядом со мной чтобы я хоть как то отреагировал на его глупые месседжи?) не ты ли?)

**Comment by forwork10** [comment]
> > > А слабо пояснить?
> > > ок, ты глупый школьник который ничего толком не умеет, но при этом думаешь что очень умный и постоянно выёбываешься) копируешь манеры своих кумиров чтобы казаться лучше. Ты дохуя раз проигрывал в спорах и уходил, высирая какой то рофл бред, а на следующий день начинал всё сначала. Ты просто ебланище которое очень хочет внимание.
> Ты блять на Луа скрипты пишешь, и мне че то предъявляешь? Да тебе и 15 нету. Что я там копирую, пример приведи (я кстати не пишу как Кохно ну ВЕЗДЕ почти, как ты)). Значит я внимания хочу?) а кто как пёсик скачет рядом со мной чтобы я хоть как то отреагировал на его глупые месседжи?) не ты ли?) 

1. покажи мои говно скрипты на луа
2. пруфы что мне нет 15

**Comment by forwork10** [comment]
а хожу я за тобой не потому что мне внимание нужно) надеюсь ты не думаешь так на полном серьёзе..

**Comment by forwork10** [comment]
да и сейчас я не хожу за тобой даже нигде) жду пока ты что то высрешь чтобы всё обрушить)

**Comment by SobakaBarabaka74** [comment]
> > > > А слабо пояснить?
> > > > ок, ты глупый школьник который ничего толком не умеет, но при этом думаешь что очень умный и постоянно выёбываешься) копируешь манеры своих кумиров чтобы казаться лучше. Ты дохуя раз проигрывал в спорах и уходил, высирая какой то рофл бред, а на следующий день начинал всё сначала. Ты просто ебланище которое очень хочет внимание.
> > > > Ты блять на Луа скрипты пишешь, и мне че то предъявляешь? Да тебе и 15 нету. Что я там копирую, пример приведи (я кстати не пишу как Кохно ну ВЕЗДЕ почти, как ты)). Значит я внимания хочу?) а кто как пёсик скачет рядом со мной чтобы я хоть как то отреагировал на его глупые месседжи?) не ты ли?)
> 
> 1. покажи мои говно скрипты на луа
> 2. пруфы что мне нет 15

Банально твой софт)) такой как ты не осилит больше чем говно на скриптовом языке который по сложности как питон блять
Да банально по твоей манере общения ясно всё уже) а когда тебя просили доказать что тебе есть там 14, ты сливался, помнишь?) это было ещё до этого давно

**Comment by forwork10** [comment]
> Банально твой софт)) такой как ты не осилит больше чем говно на скриптовом языке который по сложности как питон блять
> Да банально по твоей манере общения ясно всё уже) а когда тебя просили доказать что тебе есть там 14, ты сливался, помнишь?) это было ещё до этого давно 
>
ты всё ещё не показал мои говно скрипты и  не привёл  доки по возрасту

**Comment by forwork10** [comment]
ну вот как всегда) ты высрал, а доказать не можешь ничего

**Comment by SobakaBarabaka74** [comment]
> > Банально твой софт)) такой как ты не осилит больше чем говно на скриптовом языке который по сложности как питон блять
> > Да банально по твоей манере общения ясно всё уже) а когда тебя просили доказать что тебе есть там 14, ты сливался, помнишь?) это было ещё до этого давно
> 
> ты всё ещё не показал мои говно скрипты и не привёл доки по возрасту
Как я тебе покажу хуету эту?) ты сука сам говорил что на луа пишешь у джаста в конфе. Доки по возрасту ты должен мне кидать) я давно просил ещё раньше тебя паспорт)) а раз ты говоришь мол я не могу нечего доказать, почему же ты не докажешь "что я нечего не умею"

**Comment by forwork10** [comment]
ну вот ты не доказал нихуя как всегда, про возраст - чисто твоё мнение (но я сомневаюсь что ты так действительно думаешь). А вот скрипты - где я говорил что пишу говно скрипты((

**Comment by SobakaBarabaka74** [comment]
> ну вот ты не доказал нихуя как всегда, про возраст - чисто твоё мнение (но я сомневаюсь что ты так действительно думаешь). А вот скрипты - где я говорил что пишу говно скрипты((

Я задал вопрос - отвечай, тему не меняя

**Comment by forwork10** [comment]
какой ты вопрос задал?)

**Comment by forwork10** [comment]
я уже сделал вывод

**Comment by SobakaBarabaka74** [comment]
> я уже сделал вывод

Какой вывод, шизойд ебаный, на вопрос отвечай

**Comment by SobakaBarabaka74** [comment]
> какой ты вопрос задал?)

Раз я не могу доказать) докажи ты что я нечего не умею

**Comment by SobakaBarabaka74** [comment]
> > > какой ты вопрос задал?)
> > 
> > 
> > Раз я не могу доказать) докажи ты что я нечего не умею
> 
> ок, так как ты морально унижен, ты находишься на низшей ступени общества, соответственно, тебе просто необходимо доказать что ты лучше и чего то стоишь. И ты это делаешь - но пока что я вижу лишь дерьмо, которое сходит с твоих маленьких ручек

Ауу долбаеб, где ответ на вопрос

**Comment by SobakaBarabaka74** [comment]
Я тебе задал вопрос сцка, докажи что я нечего не умею, ты ушёл от темы

**Comment by forwork10** [comment]
> Я тебе задал вопрос сцка, докажи что я нечего не умею, ты ушёл от темы

не пытайся сделать вид что не увидел ответа) Думаю тебя этот ответ очень даже задел)) Ну если нет, то уясни что я доказал тебе что ты нихуя не умеешь) Я назвал факты которые ведут к этому

**Comment by forwork10** [comment]
вижу тебя уже разрывает))

ну ладно, повторю:
так как ты морально унижен, ты находишься на низшей ступени общества, соответственно, тебе просто необходимо доказать что ты лучше и чего то стоишь. И ты это делаешь - но пока что я вижу лишь дерьмо, которое сходит с твоих маленьких ручек. - Это доказывает что ты нихуя не умеешь, доказывает человеческая психология)) Если для тебя это не доказательства- скажи почему

**Comment by SobakaBarabaka74** [comment]
> вижу тебя уже разрывает))
> 
> ну ладно, повторю: так как ты морально унижен, ты находишься на низшей ступени общества, соответственно, тебе просто необходимо доказать что ты лучше и чего то стоишь. И ты это делаешь - но пока что я вижу лишь дерьмо, которое сходит с твоих маленьких ручек. - Это доказывает что ты нихуя не умеешь, доказывает человеческая психология)) Если для тебя это не доказательства- скажи почему

Блять... Ещё раз обьясню: поясни что я нечего не умею. Я могу сказать что я бахаю на крестах лучше чем ты, лол, ЛУА кодер))

**Comment by forwork10** [comment]
сейчас ты уже понял что обосрался, но пытаешься скрыть это.. зачем?) всем всё и так ясно. Тебе я разрешаю дальше пытаться самоутвердиться, можешь писать дальше че хочешь

**Comment by justqstn** [comment]
> > вижу тебя уже разрывает))
> > ну ладно, повторю: так как ты морально унижен, ты находишься на низшей ступени общества, соответственно, тебе просто необходимо доказать что ты лучше и чего то стоишь. И ты это делаешь - но пока что я вижу лишь дерьмо, которое сходит с твоих маленьких ручек. - Это доказывает что ты нихуя не умеешь, доказывает человеческая психология)) Если для тебя это не доказательства- скажи почему
> 
> Блять... Ещё раз обьясню: поясни что я нечего не умею. Я могу сказать что я бахаю на крестах лучше чем ты, лол, ЛУА кодер))

мак забывает, что на деле нужны практические навыки, и вылизывание своего кода тебе поможет в двух случаях: если ты пишешь гипероптимизированный код на ассемблере для микроконтроллеров, или если ты работаешь с кем-то еще
а ты что-то еще знаешь помимо базы с яп?

**Comment by justqstn** [comment]
> > > > вижу тебя уже разрывает))
> > > > ну ладно, повторю: так как ты морально унижен, ты находишься на низшей ступени общества, соответственно, тебе просто необходимо доказать что ты лучше и чего то стоишь. И ты это делаешь - но пока что я вижу лишь дерьмо, которое сходит с твоих маленьких ручек. - Это доказывает что ты нихуя не умеешь, доказывает человеческая психология)) Если для тебя это не доказательства- скажи почему
> > > 
> > > 
> > > Блять... Ещё раз обьясню: поясни что я нечего не умею. Я могу сказать что я бахаю на крестах лучше чем ты, лол, ЛУА кодер))
> > 
> > 
> > мак забывает, что на деле нужны практические навыки, и вылизывание своего кода тебе поможет в двух случаях: если ты пишешь гипероптимизированный код на ассемблере для микроконтроллеров, или если ты работаешь с кем-то еще а ты что-то еще знаешь помимо базы с яп?
> 
> Почему у всех долбаебов одно мнение о программировании: что сам яп стоит изучать как вспомогательный элемент обучения, при этом часами задрачивая алгоритмы. Нет. Эта хуйня реально юзается изредко, или по рофлу, или когда иначе нельзя написать - есть уже готовые либы для всего, тот же STL с бустом

ты долбаеб? я тебе говорю как раз-таки тоже самое
передрочил и похерил зрение? сгоняй к окулисту, если в твоем мухосранске такой имеется

**Comment by forwork10** [comment]
> > > > вижу тебя уже разрывает))
> > > > ну ладно, повторю: так как ты морально унижен, ты находишься на низшей ступени общества, соответственно, тебе просто необходимо доказать что ты лучше и чего то стоишь. И ты это делаешь - но пока что я вижу лишь дерьмо, которое сходит с твоих маленьких ручек. - Это доказывает что ты нихуя не умеешь, доказывает человеческая психология)) Если для тебя это не доказательства- скажи почему
> > > 
> > > 
> > > Блять... Ещё раз обьясню: поясни что я нечего не умею. Я могу сказать что я бахаю на крестах лучше чем ты, лол, ЛУА кодер))
> > 
> > мак забывает, что на деле нужны практические навыки, и вылизывание своего кода тебе поможет в двух случаях: если ты пишешь гипероптимизированный код на ассемблере для микроконтроллеров, или если ты работаешь с кем-то еще а ты что-то еще знаешь помимо базы с яп?
> 
> Почему у всех долбаебов одно мнение о программировании: что сам яп стоит изучать как вспомогательный элемент обучения, при этом часами задрачивая алгоритмы. Нет. Эта хуйня реально юзается изредко, или по рофлу, или когда иначе нельзя написать - есть уже готовые либы для всего, тот же STL  с бустом

ты нихуя не умеешь и высераешь чето

**Comment by AlexandroRobert** [comment]
> Ого дебаты тут... Щас все исправили, всели ок? Момент такой еще есть - проверьте версию апи в настройках режима. Хотя по умолчанию сейчас 2. Если все ок на данный момент то тему закроем

Вродебы ок

**Comment by kkohno** [comment]
закрыто, потому что проблема решена
