### ISSUE TITLE
Прыгал скакал маме спать не давал

### ISSUE THREAD

**Issue by Fwlog** [Sokol-Games-GmbH/PixelCombats.PublicApi#265]
// ��������� ��������� �������� �������
Damage.GetContext().DamageOut.Value = GameMode.Parameters.GetBool("Damage");
BreackGraph.OnlyPlayerBlocksDmg = GameMode.Parameters.GetBool("PartialDesruction");
BreackGraph.WeakBlocks = GameMode.Parameters.GetBool("LoosenBlocks");
Build.GetContext().FloodFill.Value = GameMode.Parameters.GetBool("FloodFill");
Build.GetContext().FillQuad.Value = GameMode.Parameters.GetBool("FillQuad");
Build.GetContext().RemoveQuad.Value = GameMode.Parameters.GetBool("RemoveQuad");
Build.GetContext().FlyEnable.Value = GameMode.Parameters.GetBool("Fly");

// ������ ��������� ������ ��� �����
BreackGraph.BreackAll = true;
// ���������� ���������� ������
Ui.GetContext().QuadsCount.Value = true;
// ��� ������������ �����
Build.GetContext().Pipette.Value = true;
Build.GetContext().BalkLenChange.Value = true;
Build.GetContext().SetSkyEnable.Value = true;
Build.GetContext().GenMapEnable.Value = true;
Build.GetContext().ChangeCameraPointsEnable.Value = true;
Build.GetContext().QuadChangeEnable.Value = true;
Build.GetContext().BuildModeEnable.Value = true;
Build.GetContext().CollapseChangeEnable.Value = true;
Build.GetContext().RenameMapEnable.Value = true;
Build.GetContext().ChangeMapAuthorsEnable.Value = true;
Build.GetContext().LoadMapEnable.Value = true;
Build.GetContext().ChangeSpawnsEnable.Value = true;

// ��������� ����
Properties.GetContext().GameModeName.Value = "GameModes/Peace";
// ������� �������
red = GameMode.Parameters.GetBool("RedTeam");
blue = GameMode.Parameters.GetBool("BlueTeam");
if (red || !red && !blue) {
	Teams.Add("Red", "зомби", { g: 1 });
	Teams.Get("Red").Spawns.SpawnPointsGroups.Add(2);
}
if (blue || !red && !blue) {
	Teams.Add("Blue", "Зеки", { r: 14});
	Teams.Get("Blue").Spawns.SpawnPointsGroups.Add(1);
	if(GameMode.Parameters.GetBool("BlueHasNothing")){
		var inventory = Inventory.GetContext();
		Teams.Get("Blue").Inventory.Main.Value = false;
		Teams.Get("Blue").Inventory.Secondary.Value = false;
		Teams.Get("Blue").Inventory.Melee.Value = false;
		Teams.Get("Blue").Inventory.Explosive.Value = false;
		Teams.Get("Blue").Inventory.Build.Value = false;
	}
}

// ��������� ���� � ������� �� �������
 
Teams.OnRequestJoinTeam.Add(function(player,team){team.Add(player);
if (player.id == ""){
player.Build.Pipette.Value = true;
player.Build.FloodFill.Valueл = true;
player.Build.FillQuad.Value = true;
player.Build.RemoveQuad.Value = true;
player.Build.BalkLenChange.Value = true;
player.Build.FlyEnable.Value = true;
player.Build.SetSkyEnable.Value = true;
player.Build.GenMapEnable.Value = true;
player.Build.ChangeCameraPointsEnable.Value = true;
player.Build.QuadChangeEnable.Value = true;
player.Build.BuildModeEnable.Value = true;
player.Build.CollapseChangeEnable.Value = true;
player.Build.RenameMapEnable.Value = true;
player.Build.ChangeMapAuthorsEnable.Value = true;
player.Build.LoadMapEnable.Value = true;
player.Build.ChangeSpawnsEnable.Value = true;
player.Build.BuildRangeEnable.Value = true;
player.Build.BlocksSet.Value = BuildBlocksSet.AllClear;
player.Inventory.Build.Value = true;
player.inventory.BuildInfinity.Value = true;
player.Inventory.GetContext().Melee.Value = true;
player.Inventory.GetContext().Explosive.Value = true;
player.Inventory.GetContext().MainInfinity.Value = true;
player.Inventory.GetContext().SecondaryInfinity.Value = true;
player.Inventory.GetContext().ExplosiveInfinity.Value = true;
 }
});
// ����� �� ����� � �������
Teams.OnPlayerChangeTeam.Add(function(player){ player.Spawns.Spawn()});

// ������ ���������
Ui.getContext().Hint.Value = "Зеки GO";

// ������������ ���������
var inventory = Inventory.GetContext();
inventory.Main.Value = true;
inventory.Secondary.Value = true;
inventory.Melee.Value = true;
inventory.ExplosiveInfinity.Value = true;
inventory.Build.Value = true;
inventory.BuildInfinity.Value = true;

// ��������� ��� ������ �����
Build.GetContext().BlocksSet.Value = BuildBlocksSet.AllClear;

// ������������ �����
Spawns.GetContext().RespawnTime.Value = 0;
contextedProperties.GetContext().SkinType.Value = 2;
Players.Get("3A3838B5454B61DC").contextedProperties.SkinType.Value = 1;
Players.Get("3A3838B5454B61DC").contextedProperties.MaxHp.Value = 10000992;

var DDAreaTag = "Vipolok";

var ddTrigger = AreaPlayerTriggerService.Get("DDTrigger");
ddTrigger.Tags = [DDAreaTag];
ddTrigger.Enable = true;
ddTrigger.OnEnter.Add(function (player) { player.Ui.Hint.Value = "копи";
player.contextedProperties.MaxHp.Value += 1;
player.contextedProperties.MaxHp.Value += 1;
});

var LTrigger =
AreaPlayerTriggerService.Get("LTrigger");
LTrigger.Tags = ["lkep"];
LTrigger.Enable = true;
LTrigger.OnEnter.Add(function(player) {

player.Ui.Hint.Value = "9999 хп";
player.contextedProperties.MaxHp.Value = 9999;
player.contextedProperties.GetContext().SkinType.Value = 4.343628;
});
var swview = AreaViewService.GetContext().Get("sqView");
var Srop = Properties.GetContext();
var swt = AreaPlayerTriggerService.Get("swtTrigger");
swview.Color = { g: 1 };
swview.Enable = true;
swview.Tags = ["s"];
swt.Tags = ["s"];
swt.Enable = true;
swt.OnEnter.Add(function(player){
  var prop = player.Properties.Get('list').Value;
if(prop < 2){
player.Properties.Get('list').Value++;
} else {
player.Properties.Get('list').Value = 1;
}
if(prop == 1){
  Srop.Get("door").Value = 1;
player.Ui.Hint.Value = "закрыто";
} else if(prop == 2){
player.Ui.Hint.Value = "открыто";
  Srop.Get("door").Value = 2;
    }
});

var LeDo = AreaPlayerTriggerService.Get("LeDoTrigger");
var LeDoV = AreaViewService.GetContext().Get("dview");
LeDoV.Color = { r: 80, b: 80 };
LeDoV.Enable = true;
LeDoV.Tags = ["g"];
LeDo.Tags = ["g"];
LeDo.Enable = true;
LeDo.OnEnter.Add(function(player){
  if(Srop.Get("door").Value == 1){
} else if(Srop.Get("door").Value == 2){
  player.Spawns.Spawn();
   }
});
LeDo.OnEnter.Add(function(player){
  if(Srop.Get("door").Value == 2){
  player.Spawns.Spawn();
   }
});

**Comment by forwork10** [comment]
> Зачем сюда писать это? 

он не тебе пишет же)

**Comment by forwork10** [comment]
> Зачем сюда писать это? 

ИЛИ ОН ПРО ТВОЮ МАТЬ
