### ISSUE TITLE
gamemode.json - MapLists

### ISSUE THREAD

**Issue by forwork10** [Sokol-Games-GmbH/PixelCombats.PublicApi#30]
При создании режима должен автоматически выбираться тот список карт что стоит на первом месте в поле MapLists, однако этого не происходит. Например в поле MapLists у меня есть 2 списка карт: на первом месте стоит мой список, а на 2(последнем) официальный список карт, и при создании режима выбирается официальный.

**Comment by KukushkaSex** [comment]
Он и выбирает.. Оффициальных карты для режима, это и есть списки

**Comment by forwork10** [comment]
> Он и выбирает.. Оффициальных карты для режима, это и есть списки

ты тупой, не понимаешь...

**Comment by KukushkaSex** [comment]
Ты еблаааа, зачем тебе это дурочка, там списки видны уже

**Comment by KukushkaSex** [comment]
![Uploading Screenshot_2023-08-06-12-09-13-297_com.pixel.gun.combats.jpg…]()

**Comment by kkohno** [comment]
исправлено
