### ISSUE TITLE
Какая-то лоботомия на высоких координатах

### ISSUE THREAD

**Issue by Ygoslavya** [Sokol-Games-GmbH/PixelCombats.PublicApi#343]
https://github.com/user-attachments/assets/454686ae-039e-4db4-91d2-bece8221f4a8

https://github.com/user-attachments/assets/b5737f3f-35da-4859-916d-e7b0c39f5e3f

Думаю всё же это не баг

**Comment by justqstn** [comment]
это в юнити дело, не баг
