### ISSUE TITLE
IsRequestLocalMap

### ISSUE THREAD

**Issue by KukushkaSex** [Sokol-Games-GmbH/PixelCombats.PublicApi#35]
Свойство в настройках json, которое будет позволять выбирать карта не из Оффициальных списков режима.

**Comment by KukushkaSex** [comment]
Тоесть если параметр тупо пустой, понял

**Comment by kkohno** [comment]
все верно. если вдруг будет там баг - отпишитесь. пока тему закрыл

**Comment by Kukushechka7-ezx** [comment]
@kkohno , все ок
