### ISSUE TITLE
Что-то тут не так…

### ISSUE THREAD

**Issue by Ygoslavya** [Sokol-Games-GmbH/PixelCombats.PublicApi#352]
![Screenshot_2024-10-01-19-48-25-827_com minicraft pocketedition2019](https://github.com/user-attachments/assets/9e569951-7c10-4904-9c45-d46002e7f2c2)
![Screenshot_2024-10-01-19-48-19-463_com minicraft pocketedition2019](https://github.com/user-attachments/assets/fff9629a-0e2f-4ba1-996a-f25758d36163)
Почему катана в магазине тестера стоит дороже чем в обычном магазине

**Comment by martunovZheka** [comment]
время аренды больше
