### ISSUE TITLE
Два бага с травой

### ISSUE THREAD

**Issue by Ygoslavya** [Sokol-Games-GmbH/PixelCombats.PublicApi#372]
https://github.com/user-attachments/assets/5bcb3ede-2eb4-483e-88e7-1c6efc02e6c6

https://github.com/user-attachments/assets/6091d212-7a2d-42d0-8058-d2cb49ee6982
1. Из травы нельзя вылететь
2. Через траву нельзя стрелять
935D5182612673B8

**Comment by martunovZheka** [comment]
не баги
