### ISSUE TITLE
Вода

### ISSUE THREAD

**Issue by Ygoslavya** [Sokol-Games-GmbH/PixelCombats.PublicApi#374]
https://github.com/user-attachments/assets/51e69c8b-9d92-443e-a253-bf0be9f05b38

https://github.com/user-attachments/assets/ee01ee43-e01d-4ec1-9a08-ac7709565e35

935D5182612673B8

**Comment by martunovZheka** [comment]
это не баг
Просто когда игрок в течении 7 (точно не скажу) секунд игрок не имеет коллизии с блоком, тоесть не стоит на нем - он умирает
