### ISSUE TITLE
Баг со скачиваем карт

### ISSUE THREAD

**Issue by KukushkaSex** [Sokol-Games-GmbH/PixelCombats.PublicApi#48]
Если карта уже скачена была КОГДА ЛИБО, и даже если она удалена у вас - скачивания не произойдет

**Comment by forwork10** [comment]
Ложь, карта скачивается в кэш.

**Comment by forwork10** [comment]
Ложь, карта скачивается в кэш. К тому же, сейчас вытесняем локальную загрузку, как карт, так и режимов.

**Comment by kkohno** [comment]
Если скачалась карта, то повторно не качается, потомучто она попадает в кэш... Это сделано для снижения нагрузок на сеть
