### ISSUE TITLE
Выбор режима 

### ISSUE THREAD

**Issue by KukushkaSex** [Sokol-Games-GmbH/PixelCombats.PublicApi#49]
Добавить в строку выбора режима - тот режим, в котором сейчас раздел.
![Screenshot_2023-08-12-19-59-08-091_com pixel gun combats](https://github.com/Sokol-Games-GmbH/PixelCombats.PublicApi/assets/133321399/83fdef29-d73e-4f34-95dc-a374a726b7db)
![Screenshot_2023-08-12-19-59-10-830_com pixel gun combats](https://github.com/Sokol-Games-GmbH/PixelCombats.PublicApi/assets/133321399/4dc46e6c-b158-4a21-8afb-aee944e6c3cd)

**Comment by forwork10** [comment]
Такое уже сделали, только если выбрать спсиок конкретного режима, позже сделаем так для официального типа.

**Comment by kkohno** [comment]
это окно будет дорабатываться сейчас. будет где ТДМ кнопка - список комнат а не режимов ну итд

**Comment by kkohno** [comment]
окно было переделано
