### ISSUE TITLE
Баг с названием комнаты.

### ISSUE THREAD

**Issue by KukushkaSex** [Sokol-Games-GmbH/PixelCombats.PublicApi#54]
Если не ввести не чего в название комнаты то будет непонятный текст, 1.492.
C002224F3666744D
![Screenshot_2023-08-17-03-59-52-334_com pixel gun combats](https://github.com/Sokol-Games-GmbH/PixelCombats.PublicApi/assets/133321399/0d95d813-4dfe-4b66-af96-8e139737b26c)

**Comment by kkohno** [comment]
это не баг а такое название генерируется
