### ISSUE TITLE
Редактирование карт

### ISSUE THREAD

**Issue by Kukushechka7-ezx** [Sokol-Games-GmbH/PixelCombats.PublicApi#68]
Добавить возможность редактировать описание и название карт.

**Comment by kkohno** [comment]
все верно выше описано, однако с описанием тут пожалуй можно и менять... просто новое описание не сломает игру, в отличии от изменений геометрии например

**Comment by Kukushechka7-ezx** [comment]
Сделайте смену имени тоже...

**Comment by forwork10** [comment]
нет........
