### ISSUE TITLE
Ошибка с gitHub

### ISSUE THREAD

**Issue by Kukushechka7-ezx** [Sokol-Games-GmbH/PixelCombats.PublicApi#70]
Репозиторий гитхаб не обновляется в игре и выдает ошибку, даже если он сменился на гитхабе

**Comment by forwork10** [comment]
ты просто тупой, я был прав, ты даже гитхаб првязать не можешь...

**Comment by Kukushechka7-ezx** [comment]
Хахахах ты долбаеб?) При обновлении режима с гитхаба иногда этого не происходит и выдает ошибку

**Comment by Kukushechka7-ezx** [comment]
При чем ошибок в коде нет не в файле настроек

**Comment by forwork10** [comment]
сколько раз я обновлял и ошибок небыло. ПОЧЕМУ

**Comment by kkohno** [comment]
опишите подробную инструкцию что делаете там. желательно скриншоты приложить
