### ISSUE TITLE
Баг с получением наград

### ISSUE THREAD

**Issue by Kukushechka7-ezx** [Sokol-Games-GmbH/PixelCombats.PublicApi#73]
Если сразу открыть 2 сундука то награда дается только за 1...

**Comment by forwork10** [comment]
невозможно такое... возможно просто сразу после того как показало награду с первого, открылось окно с наградой второго... награду дает за 2 сундука, просто вы можете не увидеть окно с наградой нсли нажимаете быстро. Это не баг.

**Comment by Kukushechka7-ezx** [comment]
Ххахахах спт. Ты просто новый аккаунт сделай и 2 сундука там с оружием выбей ( только они подходят ). И открой, сам узнаешь

**Comment by Kukushechka7-ezx** [comment]
Я говорю опробуй

**Comment by forwork10** [comment]
всё нормально работает, просто не всегда с сундука даёт оружие - это уже дело удачи..

**Comment by forwork10** [comment]
чего?

**Comment by Kukushechka7-ezx** [comment]
??

**Comment by kkohno** [comment]
тут нужно проверять... вобще там да - на сервере обработка этого всего... там ошибок замечено небыло

**Comment by forwork10** [comment]
аххаха обосрался мак
