### ISSUE TITLE
предложение - понизить минимальный интервал таймера до 0.1 или 0.01

### ISSUE THREAD

**Issue by justqstn** [Sokol-Games-GmbH/PixelCombats.PublicApi#76]
помню, на подобный вопрос вы отвечали что там лаги будут, но это уже от самого кода зависит

**Comment by Kukushechka7-ezx** [comment]
Не нужно городить махинации с датой, ок

**Comment by justqstn** [comment]
твои махинации с датой не работают, ты в однопоточном языке ничего такого не сделаешь...

**Comment by kkohno** [comment]
таймер специально ограничили, чтобы небыло флуда

**Comment by justqstn** [comment]
какой еще флуд? пусть игроки делают, что хотят, на вас это как повлияет?

**Comment by Kukushechka7-ezx** [comment]
Работает) навязать игроку событие и все,лоол

**Comment by justqstn** [comment]
кинь сюда код, потом поговорим

**Comment by Kukushechka7-ezx** [comment]
Слишком крутое пока что - в шифре дать?

**Comment by justqstn** [comment]
хаха ну дай)) слишком крутое оно
в действие покажи мне))

**Comment by kkohno** [comment]
по соображениям производительности и безопасности такое не делаем. ограничение итак очень незначительное... 0.1 сек это уже очень часто
