### ISSUE TITLE
Локальные режимы

### ISSUE THREAD

**Issue by Kukushechka7-ezx** [Sokol-Games-GmbH/PixelCombats.PublicApi#77]
У тех кого нет пк трудно тестировать режимы... Для этого предлагаю добавить возможность загрузки локальных режимов, из файлов игры

**Comment by kkohno** [comment]
С трудом себе представляю, что можно запрограммировать что-либо без пк... Смысл?

**Comment by Kukushechka7-ezx** [comment]
Много чего... Очень много, а в чем проблема писать с телефона

**Comment by forwork10** [comment]
аххаха ты просто бомж у тебя пк нет))

**Comment by forwork10** [comment]
сидишь там со своего дешевого маленького телефончика печатаешь))) нищий) никто под тебя подстраиваться не будет, если ты нищий - твои проблемы.

**Comment by Kukushechka7-ezx** [comment]
Мне напомнить, как ты говорил что ты бездомен и у тебя нет пк?)

**Comment by kkohno** [comment]
всетаки расчитывать на то, что с телефона будет кодинг мы не станем. Раздобудьте хоть какой-то б/у ноутбук, поставьте туда простейшую IDE, например Visual Studio Code. Тогда это кодинг, предполагающий результат

**Comment by Kukushechka7-ezx** [comment]
У меня то есть - но что про других+200 игроков?

**Comment by justqstn** [comment]
покажи мне из этих 200 игроков нормальных кодеров

**Comment by Kukushechka7-ezx** [comment]
Нормальных? А зачем нормальных

**Comment by justqstn** [comment]
им предоставлять возможности нету смысла, они делать ничего не хотят и не захотят

**Comment by Kukushechka7-ezx** [comment]
А другие? Если кто то захочет

**Comment by forwork10** [comment]
> У меня то есть - но что про других+200 игроков?

у тебя как раз таки нету) не стал бы беспокоиться за других
